/* DO NOT EDIT THIS FILE - it is machine generated */
#include <string.h>
#include<stdio.h>
#include<errno.h>
#include<unistd.h>
#include<fcntl.h>
#include <linux/ioctl.h>
#include"ModuleManager.h"

#define OW_IOCTL 0xF4
#define IOCTL_POWER_ALWAYS_ON _IOW(OW_IOCTL, 0, int)
#define IOCTL_POWER_ON  _IO(OW_IOCTL, 1)
#define IOCTL_POWER_OFF _IO(OW_IOCTL, 2)
#define IOCTL_POWER_STATUS _IOR(OW_IOCTL, 3, int)
#define IOCTL_POWER_ALWAYS_ON_STATUS _IOR(OW_IOCTL, 4, int)
/* Header for class com_rodinbell_Module_ModuleManager */
#include "android/log.h"
static const char *TAG="module_manager";
#define LOGI(fmt, args...) __android_log_print(ANDROID_LOG_INFO,  TAG, fmt, ##args)
#define LOGD(fmt, args...) __android_log_print(ANDROID_LOG_DEBUG, TAG, fmt, ##args)
#define LOGE(fmt, args...) __android_log_print(ANDROID_LOG_ERROR, TAG, fmt, ##args)

#ifdef __cplusplus
extern "C" {
#endif
//device path
char *path_scanner_old = "sys/class/gpio/gpio204/value";
char *path_uhf_rfid_old = "sys/class/gpio/gpio200/value";

char *path_uhf_rfid = "/dev/rfid";
char *path_barcode = "/dev/barcode";

const int dev_uhf = 0;
const int dev_scanner = 1;

int fdRFID = -1;
int RFIDOpenType; // 0: gpio; 1: dev
int fdScan = -1;
int ScanOpenType;

/*
 * Class:     com_rodinbell_Module_ModuleManager
 * Method:    JINWriteGPIO
 * Signature: (II)I
 */
int checkOpen(int devNo)
{
    if (devNo == dev_uhf) {
        if (fdRFID < 0) {
            fdRFID = open(path_uhf_rfid_old, O_RDWR | O_APPEND);
            if (fdRFID < 0) {
                fdRFID = open(path_uhf_rfid, O_RDWR);
                if (fdRFID < 0) {
                    return -1;
                } else {
                    RFIDOpenType = 1;
                }
            } else {
                RFIDOpenType = 0;//0 is gpio
            }
        };
    }
    if (devNo == dev_scanner) {
        if (fdScan < 0) {
            fdScan = open(path_scanner_old, O_RDWR | O_APPEND);
            if (fdScan < 0) {
                fdScan = open(path_barcode, O_RDWR);
                if (fdScan < 0) {
                    return -1;
                } else {
                    ScanOpenType = 1;
                }
            } else {
                ScanOpenType = 0;
            }
        };
    }
    return 0;
}

int setValue(int devNo, int value) {
    int fd;
    int type;
    int alway_on = 0;
    if (devNo == dev_uhf) {
        fd = fdRFID;
        type = RFIDOpenType;
    } else if (devNo == dev_scanner) {
        fd = fdScan;
        type = ScanOpenType;
    }

    if (!type) {
        char *ch;
        if (value) {
            ch = "1\n";
        } else {
            ch = "0\n";
        }
        char buf[10];
        memset(buf, 0, sizeof(buf));
        strcpy(buf, ch);
        write(fd, buf, strlen(buf));
    } else {
        switch (value) {
            case 0:
                if (ioctl(fd, IOCTL_POWER_OFF, NULL) < 0) {
                    return -1;
                }
                break;
            case 1:
                if (ioctl(fd, IOCTL_POWER_ON, NULL) < 0) {
                    return -1;
                }
                break;
            case 2:   // always_on off
                alway_on = 0;
                if (ioctl(fd, IOCTL_POWER_ALWAYS_ON, &alway_on) < 0) {
                    return -1;
                }
                break;
            case 3:    // always_on on
                alway_on = 1;
                if (ioctl(fd, IOCTL_POWER_ALWAYS_ON, &alway_on) < 0) {
                    return -1;
                }
                break;
        }
    }
    return 0;
}
int getValue(int devNo,int isAlways) {
    int fd;
    int type;
    int value;
    if (devNo == dev_uhf) {
        fd = fdRFID;
        type = RFIDOpenType;
    } else if (devNo == dev_scanner) {
        fd = fdScan;
        type = ScanOpenType;
    }

    if (!type) {
        char buf[10];
        while (read(fd, buf, sizeof(buf)) > 0) {
        }
        if (buf[0] == 49) {
            return 1;
        } else if (buf[0] == 48) {
            return 0;
        }
    } else {
        switch (isAlways) {
            case 0:
                if (ioctl(fd, IOCTL_POWER_STATUS, &value) < 0) {
                    return -1;
                }
                break;
            case 1:
                if (ioctl(fd, IOCTL_POWER_ALWAYS_ON_STATUS, &value) < 0) {
                    return -1;
                }
                break;
        }
    }
    return value;
}
int checkClose(int devNo)
{
    if (devNo == dev_uhf) {
        if (!RFIDOpenType) {
            close(fdRFID);
            fdRFID = -1;
        }
    } else if (devNo == dev_scanner) {
        if (!ScanOpenType) {
            close(fdScan);
            fdScan = -1;
        }
    }
}

JNIEXPORT jint JNICALL Java_com_naz_serial_port_ModuleManager_JNIWriteGPIO
		(JNIEnv *env, jobject thiz, jint value, jint devNo) {
           LOGD("Opening value = %d devNo = %d",value,devNo);
            int ret = 1;
            if (checkOpen(devNo)) {
                LOGD("Open error! value = %d devNo = %d",value,devNo);
                return 0;
            }
            if (setValue(devNo, value))
                ret = 0;

            LOGD("Open success! fd = %d-%d type = %d-%d ret = %d",fdRFID,fdScan,RFIDOpenType,ScanOpenType,ret);
            checkClose(devNo);
            return ret;
}

/*
 * Class:     com_rodinbell_Module_ModuleManager
 * Method:    JINReadGPIO
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_naz_serial_port_ModuleManager_JNIReadGPIO
		(JNIEnv *env, jobject thiz, jint devNo,jint isAlways) {
    int ret = -1;
    if (checkOpen(devNo))
        return -1;
    ret = getValue(devNo,isAlways);

    checkClose(devNo);
    return ret;
}

JNIEXPORT jint JNICALL Java_com_naz_serial_port_ModuleManager_JNIRelease(JNIEnv *evn,jobject thiz) {
    int ret = -1;
        if (fdRFID) {
            ret = close(fdRFID);
            fdRFID = -1;
        if (fdScan) {
            ret = close(fdScan);
            fdScan = -1;
        }
    }
}

#ifdef __cplusplus
}
#endif
