/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rodinbell_Module_ModuleManager */

#ifndef _Included_com_rodinbell_Module_ModuleManager
#define _Included_com_rodinbell_Module_ModuleManager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_rodinbell_Module_ModuleManager_OFF
#define com_rodinbell_Module_ModuleManager_OFF 0L
#undef com_rodinbell_Module_ModuleManager_ON
#define com_rodinbell_Module_ModuleManager_ON 1L
#undef com_rodinbell_Module_ModuleManager_SET_SUCCESSED
#define com_rodinbell_Module_ModuleManager_SET_SUCCESSED 1L
#undef com_rodinbell_Module_ModuleManager_SET_FAILED
#define com_rodinbell_Module_ModuleManager_SET_FAILED 0L
#undef com_rodinbell_Module_ModuleManager_HUF_DEV_NO
#define com_rodinbell_Module_ModuleManager_HUF_DEV_NO 200L
#undef com_rodinbell_Module_ModuleManager_SCAN_DEV_NO
#define com_rodinbell_Module_ModuleManager_SCAN_DEV_NO 204L
#undef com_rodinbell_Module_ModuleManager_MOTO_DEV_NO
#define com_rodinbell_Module_ModuleManager_MOTO_DEV_NO 237L
/*
 * Class:     com_rodinbell_Module_ModuleManager
 * Method:    JINWriteGPIO
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_naz_serial_port_ModuleManager_JNIWriteGPIO
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_rodinbell_Module_ModuleManager
 * Method:    JINReadGPIO
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_naz_serial_port_ModuleManager_JNIReadGPIO
  (JNIEnv *, jobject, jint,jint);

JNIEXPORT jint JNICALL Java_com_naz_serial_port_ModuleManager_JNIRelease(JNIEnv *evn,jobject thiz);

#ifdef __cplusplus
}
#endif
#endif
