/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_winplus_serial_utils_SerialPort */

#ifndef _Included_org_winplus_serial_utils_SerialPort
#define _Included_org_winplus_serial_utils_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL
Java_com_naz_serial_port_SerialPort_open(JNIEnv *, jclass, jstring, jint,
                                         jint flags);

/*
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_naz_serial_port_SerialPort_close(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
